[package]
name = "bbscript"
version = "0.6.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33"
byteorder = "1.3"
serde = { version = "1.0", features = ['derive'] }
thiserror = "1.0"
ron = "0.5"
bimap = { version = "0.4", features = ['serde'] }
bytes = "0.5.4"
hex = "0.4.2"
pest_derive = "2.1.0"
pest_consume = "1.0.5"
pest = "2.1.3"
